[package]
name = "send-tx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
borsh = "1.5.1"
solana-rpc-client = "2.0.4"
solana-sdk = "2.0.4"